import { ref, get, push, set } from 'firebase/database';

import { db } from '@/firebase';

/**
 * Interface defining a heartbeat preset configuration.
 */
export interface HeartbeatPreset {
    id: string; // Unique identifier (generated by Firebase)
    label: string; // User-friendly label (e.g., "Calm", "Fast Pulse")
    beatsPerMinute: number; // BPM of the simulated heartbeat
    vibrationFrequencyHz: number; // Vibration frequency in Hz
    amplitude: number; // Vibration amplitude (0.0 to 1.0)
}

/**
 * Fetches all saved heartbeat presets from Firebase.
 *
 * @returns An array of HeartbeatPreset objects
 */
export const fetchHeartbeatPresets = async (): Promise<HeartbeatPreset[]> => {
    const snapshot = await get(ref(db, '/presets/heartbeat'));
    if (!snapshot.exists()) return [];

    const data = snapshot.val();

    // Convert the object map into an array with IDs included
    return Object.entries(data).map(([id, value]) => ({
        id,
        ...(value as Omit<HeartbeatPreset, 'id'>),
    }));
};

/**
 * Activates a heartbeat preset by writing it to the /commands/heartbeat path.
 *
 * @param preset - The preset settings (without the ID) to activate
 */
export const activateHeartbeatPreset = async (
    preset: Omit<HeartbeatPreset, 'id'>
): Promise<void> => {
    const newRef = ref(db, '/commands/heartbeat');
    await set(newRef, preset);
};

/**
 * Saves a custom heartbeat preset to Firebase under /presets/heartbeat.
 * Firebase generates a unique ID via `push()`.
 *
 * @param preset - The preset configuration to save
 */
export const saveCustomHeartbeatPreset = async (
    preset: Omit<HeartbeatPreset, 'id'>
): Promise<void> => {
    const newRef = push(ref(db, '/presets/heartbeat')); // Auto-generate ID
    await set(newRef, preset);
};

/**
 * Fetches the currently active heartbeat configuration.
 * This is used to sync the UI or hardware with the current state.
 *
 * @returns The active heartbeat preset or null if none is set
 */
export const fetchActiveHeartbeatSetting =
    async (): Promise<HeartbeatPreset | null> => {
        const snapshot = await get(ref(db, '/commands/heartbeat'));
        if (!snapshot.exists()) return null;

        return snapshot.val() as HeartbeatPreset;
    };
